DROP TABLE IF EXISTS TBL_EMPLOYEES;
  
CREATE TABLE TBL_PRODUCT (
  product_id INT AUTO_INCREMENT  PRIMARY KEY,
  product_name VARCHAR(250) NOT NULL,
  product_company VARCHAR(250) NOT NULL,
  product_price DOUBLE DEFAULT NULL,
  product_picbyte BLOB   DEFAULT NULL
);

CREATE SEQUENCE HIBERNATE_SEQUENCE start with 3 increment by 1 ;